openapi: 3.0.1
info:
  title: User API
  description: User API.
  version: 1.0.0
servers:
- url: https://example.swagger.io/v1
paths:
  /user:
    post:
      summary: Creates a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request. User ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '500':
          description: Internal server error
      x-codegen-request-body-name: user
  /user/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
      - name: userId
        in: path
        description: The ID of the user to return.
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          pattern: '^[a-z]+$'
        email:
          type: string
        mobile:
          type: array
          items:
            type: string
        address:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Address:
      required:
      - id
      - name
      type: object
      properties:
        city:
          type: string
        street:
          type: string
          maxLength: 40